<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<title>
Login
</title>
<link rel="stylesheet" href="/css/style.css" />
</head>
<body>
<div class="loginPanel">
<form action="" method="POST">
	<div class="loginText">
		Login PlaceManager
	</div>
	<div class="loginUserName">
		<div class="luser">User Name</div><div class="namediv"><input class="nameinput" name="name" /></div>
		<div class="clear"></div>
	</div>
	<div class="loginPassword">
		<div class="lpwd">Password</div><div class="pwddiv"><input name="password" /></div>
		<div class="clear"></div>
	</div>
	<div class="loginCapta">
		
	</div>
	<div class="loginSubmit">
		<input type="submit" />
	</div>
</form>
</div>
</body>
</html>